version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express_backend
    env_file:
      - ./backend/.env # Load environment variables from backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    command: yarn run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    env_file:
      - ./frontend/.env # Load environment variables from frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    command: yarn run dev

volumes:
  postgres_data:
